server:
  port: 8080
spring:
  application:
    name: sch-owl
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 50
        max-idle: 20
        max-wait: 5000
        min-idle: 0
    password: 123456a!
    port: 16379
    timeout: 6000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.1:13306/sch_owl?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456a!
    druid:
      validation-query: select 1 from DUAL
      validation-query-timeout: 5000
      test-while-idle: true
      test-on-borrow: false
      max-active: 10
      max-wait: 60000
      min-idle: 5
      initial-size: 5
      max-wait-thread-count: 20
      time-between-eviction-runs-millis: 2000


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0

mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.sch.owl.infrastructure.entity